### ISSUE TITLE
Error installing, package ‘truncnorm’ is not available (for R version 3.3.3) 

### ISSUE THREAD

**Issue by ArtCardenas** [olafmersmann/truncnorm#1]
> install.packages("truncnorm",repos = "https://cran.r-project.org")
Installing package into ‘C:/Users/Art/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
Warning message:
package ‘truncnorm’ is not available (for R version 3.3.3)

**Comment by ndukler** [comment]
This is also a problem for me. Is truncnorm not backwards compatible?

**Comment by samthiriot** [comment]
hey ! Tks for the nice package! But same question here: the version required is still quiet rare in many linux distributions, so it makes me reluctant adding a dependancy to this package, which will restrict the proportion of potential users :-/ Is this version number really necessary?

**Comment by mararie** [comment]
you can find older versions of the package here: [https://cran.r-project.org/src/contrib/Archive/truncnorm/](url)
you can install these from source. version 1.0-7 works with R version 3.2.3

**Comment by muschellij2** [comment]
Does that imply that truncnorm version 1.08 doesnt work with 3.3.3?

**Comment by muschellij2** [comment]
It looks like truncnorm `R (>= 3.4.0)` requirement is overly stringent https://travis-ci.com/muschellij2/truncnorm (Linux and OSX) and https://ci.appveyor.com/project/muschellij2/truncnorm (checking on Windows)

**Comment by ArtCardenas** [comment]
fixed now

    On Tuesday, February 26, 2019, 4:31:48 PM EST, John Muschelli <notifications@github.com> wrote:  
 
 
Does that imply that truncnorm version 1.08 doesnt work with 3.3.3?

**Comment by ArtCardenas** [comment]
fixed now

    On Tuesday, February 26, 2019, 4:43:48 PM EST, John Muschelli <notifications@github.com> wrote:  
 
 
It looks like truncnorm R (>= 3.4.0) requirement is overly stringent https://travis-ci.com/muschellij2/truncnorm (Linux and OSX) and https://ci.appveyor.com/project/muschellij2/truncnorm (checking on Windows)

**Comment by muschellij2** [comment]
It's not fixed. I've sent a PR; but not fixed until merged.

**Comment by olafmersmann** [comment]
Is this still an issue for people? If so, I can spin a release with reduced version requirements.

**Comment by ArtCardenas** [comment]
Hi,  wow, this from 2019, and we are in 2023, almost 5 years ago.  

yes, the issue was fixed 5 years ago.

thanks.

**Comment by olafmersmann** [comment]
Sorry for the delay, `truncnorm` is in maintenance mode and I haven't looked at the filed issues in ages :/
