### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by jaquetjm** [olafmersmann/truncnorm#5]
I have dowloaded truncnorm_1.0-8.tar from CRAN archive and stored it locally. In R 3.6.0, trying "Install package(s) from local file", I get the following:
------------------------------------------------------------------------------
> utils:::menuInstallLocal()
* installing *source* package 'truncnorm' ...
** package 'truncnorm' correctement décompressé et sommes MD5 vérifiées (=correctly decompressed)
** using staged installation
** libs
*** arch - i386
Warning in system(cmd) : 'make' not found
ERROR: compilation failed for package 'truncnorm'
* removing 'D:/Mes documents/R/win-library/3.6/truncnorm'
Warning message:
In install.packages(files[tarballs], .libPaths()[1L], repos = NULL,  :
  l'installation du package ‘C:/PROGRA~1/R/R_PACK~1/truncnorm_1.0-8.tar.gz’ a eu un statut de sortie non nul
---------------------------------------------------------
Is the problem due to uncompatibility between R latest version and truncnorm?

**Comment by olafmersmann** [comment]
You're probably missing the [Rtools](https://cran.r-project.org/bin/windows/Rtools/).
