### ISSUE TITLE
Fatal error when calling truncnorm from fitdistrplus

### ISSUE THREAD

**Issue by m-schiavoni** [olafmersmann/truncnorm#6]
The following code causes a fatal error that crashes R.
```
library(fitdistrplus)
library(truncnorm)
set.seed(0)
x = rtruncnorm(n=30, a=0, b=Inf, mean=1, sd=0.45)
my_fit = fitdist(x, "truncnorm", method='mle', fix.arg=list(a=0, b=Inf), start=list(mean=mean(x), sd=sd(x)))
```

more details: https://stackoverflow.com/questions/63432316/fitting-truncnorm-distribution-with-distrplus-causes-fatal-error-r-crashes/

**Comment by wiz21b** [comment]
Please note that some cool SO user has debugged the root cause. See [here](https://stackoverflow.com/questions/72032290/r-crashes-when-fitting-truncated-normal-distribution).

**Comment by olafmersmann** [comment]
Thanks for debugging this and sorry for the long delay before the fix.
